### ISSUE TITLE
Improve: Improve the UI of edit-post by Implementing icons to buttons

### ISSUE THREAD

**Issue by SAGARSINGH-1** [SAGARSINGH-1/CodeAndBlog#49]
Improve UI of edit-page by implementing "Edit" and "Delete" icons as in replace of buttons.

<img width="531" alt="image" src="https://github.com/SAGARSINGH-1/CodeAndBlog/assets/81561733/3515fe7b-d94e-4719-8584-f48a932daed6">

Reference : Use icons from : "https://react-icons.github.io/react-icons/"

**Comment by Yuwen-0** [comment]
Hello i want to work on this but i cant fnd where the edit-page is

**Comment by SAGARSINGH-1** [comment]
Hey, @Yuwen-0 could u join our discord, to get access to server credentials to work on this issue.
